// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.android.launcher3.logger;

@SuppressWarnings("hiding")
public interface LauncherAtom {

  // enum Attribute
  public interface Attribute {
    public static final int UNKNOWN = 0;
    public static final int DEFAULT_LAYOUT = 1;
    public static final int BACKUP_RESTORE = 2;
    public static final int PINITEM = 3;
    public static final int ALLAPPS_ATOZ = 4;
    public static final int WIDGETS = 5;
    public static final int ADD_TO_HOMESCREEN = 6;
    public static final int ALLAPPS_PREDICTION = 7;
    public static final int HOTSEAT_PREDICTION = 8;
    public static final int SUGGESTED_LABEL = 9;
    public static final int MANUAL_LABEL = 10;
    public static final int UNLABELED = 11;
    public static final int EMPTY_LABEL = 12;
  }

  // enum FromState
  public interface FromState {
    public static final int FROM_STATE_UNSPECIFIED = 0;
    public static final int FROM_EMPTY = 1;
    public static final int FROM_CUSTOM = 2;
    public static final int FROM_SUGGESTED = 3;
  }

  // enum ToState
  public interface ToState {
    public static final int TO_STATE_UNSPECIFIED = 0;
    public static final int UNCHANGED = 1;
    public static final int TO_SUGGESTION0 = 2;
    public static final int TO_SUGGESTION1_WITH_VALID_PRIMARY = 3;
    public static final int TO_SUGGESTION1_WITH_EMPTY_PRIMARY = 4;
    public static final int TO_SUGGESTION2_WITH_VALID_PRIMARY = 5;
    public static final int TO_SUGGESTION2_WITH_EMPTY_PRIMARY = 6;
    public static final int TO_SUGGESTION3_WITH_VALID_PRIMARY = 7;
    public static final int TO_SUGGESTION3_WITH_EMPTY_PRIMARY = 8;
    public static final int TO_EMPTY_WITH_VALID_PRIMARY = 9;
    public static final int TO_EMPTY_WITH_VALID_SUGGESTIONS_AND_EMPTY_PRIMARY = 10;
    public static final int TO_EMPTY_WITH_EMPTY_SUGGESTIONS = 11;
    public static final int TO_EMPTY_WITH_SUGGESTIONS_DISABLED = 12;
    public static final int TO_CUSTOM_WITH_VALID_PRIMARY = 13;
    public static final int TO_CUSTOM_WITH_VALID_SUGGESTIONS_AND_EMPTY_PRIMARY = 14;
    public static final int TO_CUSTOM_WITH_EMPTY_SUGGESTIONS = 15;
    public static final int TO_CUSTOM_WITH_SUGGESTIONS_DISABLED = 16;
  }

  public static final class ItemInfo extends
      com.google.protobuf.nano.MessageNano {
    public static final int APPLICATION_FIELD_NUMBER = 1;
    public static final int TASK_FIELD_NUMBER = 2;
    public static final int SHORTCUT_FIELD_NUMBER = 3;
    public static final int WIDGET_FIELD_NUMBER = 4;
    public static final int FOLDER_ICON_FIELD_NUMBER = 9;
    private int itemCase_ = 0;
    private Object item_;
    public int getItemCase() {
      return this.itemCase_;
    }
    public ItemInfo clearItem() {
      this.itemCase_ = 0;
      this.item_ = null;
      return this;
    }

    private static volatile ItemInfo[] _emptyArray;
    public static ItemInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ItemInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .Application application = 1;
    public boolean hasApplication() {
      return this.itemCase_ == 1;
    }
    public Application getApplication() {
      if (this.itemCase_ == 1) {
        return (Application) this.item_;
      }
      return null;
    }
    public ItemInfo setApplication(Application value) {
      if (value == null) { throw new NullPointerException(); }
      this.itemCase_ = 1;
      this.item_ = value;
      return this;
    }

    // optional .Task task = 2;
    public boolean hasTask() {
      return this.itemCase_ == 2;
    }
    public Task getTask() {
      if (this.itemCase_ == 2) {
        return (Task) this.item_;
      }
      return null;
    }
    public ItemInfo setTask(Task value) {
      if (value == null) { throw new NullPointerException(); }
      this.itemCase_ = 2;
      this.item_ = value;
      return this;
    }

    // optional .Shortcut shortcut = 3;
    public boolean hasShortcut() {
      return this.itemCase_ == 3;
    }
    public Shortcut getShortcut() {
      if (this.itemCase_ == 3) {
        return (Shortcut) this.item_;
      }
      return null;
    }
    public ItemInfo setShortcut(Shortcut value) {
      if (value == null) { throw new NullPointerException(); }
      this.itemCase_ = 3;
      this.item_ = value;
      return this;
    }

    // optional .Widget widget = 4;
    public boolean hasWidget() {
      return this.itemCase_ == 4;
    }
    public Widget getWidget() {
      if (this.itemCase_ == 4) {
        return (Widget) this.item_;
      }
      return null;
    }
    public ItemInfo setWidget(Widget value) {
      if (value == null) { throw new NullPointerException(); }
      this.itemCase_ = 4;
      this.item_ = value;
      return this;
    }

    // optional .FolderIcon folder_icon = 9;
    public boolean hasFolderIcon() {
      return this.itemCase_ == 9;
    }
    public FolderIcon getFolderIcon() {
      if (this.itemCase_ == 9) {
        return (FolderIcon) this.item_;
      }
      return null;
    }
    public ItemInfo setFolderIcon(FolderIcon value) {
      if (value == null) { throw new NullPointerException(); }
      this.itemCase_ = 9;
      this.item_ = value;
      return this;
    }

    // optional int32 rank = 5;
    public int rank;

    // optional bool is_work = 6;
    public boolean isWork;

    // optional .ContainerInfo container_info = 7;
    public ContainerInfo containerInfo;

    // optional .Attribute attribute = 8;
    public int attribute;

    public ItemInfo() {
      clear();
    }

    public ItemInfo clear() {
      rank = 0;
      isWork = false;
      containerInfo = null;
      attribute = Attribute.UNKNOWN;
      clearItem();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.itemCase_ == 1) {
        output.writeMessage(1,
            (com.google.protobuf.nano.MessageNano) this.item_);
      }
      if (this.itemCase_ == 2) {
        output.writeMessage(2,
            (com.google.protobuf.nano.MessageNano) this.item_);
      }
      if (this.itemCase_ == 3) {
        output.writeMessage(3,
            (com.google.protobuf.nano.MessageNano) this.item_);
      }
      if (this.itemCase_ == 4) {
        output.writeMessage(4,
            (com.google.protobuf.nano.MessageNano) this.item_);
      }
      if (this.rank != 0) {
        output.writeInt32(5, this.rank);
      }
      if (this.isWork != false) {
        output.writeBool(6, this.isWork);
      }
      if (this.containerInfo != null) {
        output.writeMessage(7, this.containerInfo);
      }
      if (this.attribute != Attribute.UNKNOWN) {
        output.writeInt32(8, this.attribute);
      }
      if (this.itemCase_ == 9) {
        output.writeMessage(9,
            (com.google.protobuf.nano.MessageNano) this.item_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.itemCase_ == 1) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1,
              (com.google.protobuf.nano.MessageNano) this.item_);
      }
      if (this.itemCase_ == 2) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2,
              (com.google.protobuf.nano.MessageNano) this.item_);
      }
      if (this.itemCase_ == 3) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3,
              (com.google.protobuf.nano.MessageNano) this.item_);
      }
      if (this.itemCase_ == 4) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(4,
              (com.google.protobuf.nano.MessageNano) this.item_);
      }
      if (this.rank != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.rank);
      }
      if (this.isWork != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(6, this.isWork);
      }
      if (this.containerInfo != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(7, this.containerInfo);
      }
      if (this.attribute != Attribute.UNKNOWN) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(8, this.attribute);
      }
      if (this.itemCase_ == 9) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(9,
              (com.google.protobuf.nano.MessageNano) this.item_);
      }
      return size;
    }

    @Override
    public ItemInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (!(this.itemCase_ == 1)) {
              this.item_ = new Application();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.item_);
            this.itemCase_ = 1;
            break;
          }
          case 18: {
            if (!(this.itemCase_ == 2)) {
              this.item_ = new Task();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.item_);
            this.itemCase_ = 2;
            break;
          }
          case 26: {
            if (!(this.itemCase_ == 3)) {
              this.item_ = new Shortcut();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.item_);
            this.itemCase_ = 3;
            break;
          }
          case 34: {
            if (!(this.itemCase_ == 4)) {
              this.item_ = new Widget();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.item_);
            this.itemCase_ = 4;
            break;
          }
          case 40: {
            this.rank = input.readInt32();
            break;
          }
          case 48: {
            this.isWork = input.readBool();
            break;
          }
          case 58: {
            if (this.containerInfo == null) {
              this.containerInfo = new ContainerInfo();
            }
            input.readMessage(this.containerInfo);
            break;
          }
          case 64: {
            int value = input.readInt32();
            switch (value) {
              case Attribute.UNKNOWN:
              case Attribute.DEFAULT_LAYOUT:
              case Attribute.BACKUP_RESTORE:
              case Attribute.PINITEM:
              case Attribute.ALLAPPS_ATOZ:
              case Attribute.WIDGETS:
              case Attribute.ADD_TO_HOMESCREEN:
              case Attribute.ALLAPPS_PREDICTION:
              case Attribute.HOTSEAT_PREDICTION:
              case Attribute.SUGGESTED_LABEL:
              case Attribute.MANUAL_LABEL:
              case Attribute.UNLABELED:
              case Attribute.EMPTY_LABEL:
                this.attribute = value;
                break;
            }
            break;
          }
          case 74: {
            if (!(this.itemCase_ == 9)) {
              this.item_ = new FolderIcon();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.item_);
            this.itemCase_ = 9;
            break;
          }
        }
      }
    }

    public static ItemInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ItemInfo(), data);
    }

    public static ItemInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ItemInfo().mergeFrom(input);
    }
  }

  public static final class ContainerInfo extends
      com.google.protobuf.nano.MessageNano {
    public static final int WORKSPACE_FIELD_NUMBER = 1;
    public static final int HOTSEAT_FIELD_NUMBER = 2;
    public static final int FOLDER_FIELD_NUMBER = 3;
    public static final int ALL_APPS_CONTAINER_FIELD_NUMBER = 4;
    public static final int WIDGETS_CONTAINER_FIELD_NUMBER = 5;
    public static final int PREDICTION_CONTAINER_FIELD_NUMBER = 6;
    public static final int SEARCH_RESULT_CONTAINER_FIELD_NUMBER = 7;
    public static final int SHORTCUTS_CONTAINER_FIELD_NUMBER = 8;
    public static final int SETTINGS_CONTAINER_FIELD_NUMBER = 9;
    public static final int PREDICTED_HOTSEAT_CONTAINER_FIELD_NUMBER = 10;
    public static final int TASK_SWITCHER_CONTAINER_FIELD_NUMBER = 11;
    private int containerCase_ = 0;
    private Object container_;
    public int getContainerCase() {
      return this.containerCase_;
    }
    public ContainerInfo clearContainer() {
      this.containerCase_ = 0;
      this.container_ = null;
      return this;
    }

    private static volatile ContainerInfo[] _emptyArray;
    public static ContainerInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ContainerInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .WorkspaceContainer workspace = 1;
    public boolean hasWorkspace() {
      return this.containerCase_ == 1;
    }
    public WorkspaceContainer getWorkspace() {
      if (this.containerCase_ == 1) {
        return (WorkspaceContainer) this.container_;
      }
      return null;
    }
    public ContainerInfo setWorkspace(WorkspaceContainer value) {
      if (value == null) { throw new NullPointerException(); }
      this.containerCase_ = 1;
      this.container_ = value;
      return this;
    }

    // optional .HotseatContainer hotseat = 2;
    public boolean hasHotseat() {
      return this.containerCase_ == 2;
    }
    public HotseatContainer getHotseat() {
      if (this.containerCase_ == 2) {
        return (HotseatContainer) this.container_;
      }
      return null;
    }
    public ContainerInfo setHotseat(HotseatContainer value) {
      if (value == null) { throw new NullPointerException(); }
      this.containerCase_ = 2;
      this.container_ = value;
      return this;
    }

    // optional .FolderContainer folder = 3;
    public boolean hasFolder() {
      return this.containerCase_ == 3;
    }
    public FolderContainer getFolder() {
      if (this.containerCase_ == 3) {
        return (FolderContainer) this.container_;
      }
      return null;
    }
    public ContainerInfo setFolder(FolderContainer value) {
      if (value == null) { throw new NullPointerException(); }
      this.containerCase_ = 3;
      this.container_ = value;
      return this;
    }

    // optional .AllAppsContainer all_apps_container = 4;
    public boolean hasAllAppsContainer() {
      return this.containerCase_ == 4;
    }
    public AllAppsContainer getAllAppsContainer() {
      if (this.containerCase_ == 4) {
        return (AllAppsContainer) this.container_;
      }
      return null;
    }
    public ContainerInfo setAllAppsContainer(AllAppsContainer value) {
      if (value == null) { throw new NullPointerException(); }
      this.containerCase_ = 4;
      this.container_ = value;
      return this;
    }

    // optional .WidgetsContainer widgets_container = 5;
    public boolean hasWidgetsContainer() {
      return this.containerCase_ == 5;
    }
    public WidgetsContainer getWidgetsContainer() {
      if (this.containerCase_ == 5) {
        return (WidgetsContainer) this.container_;
      }
      return null;
    }
    public ContainerInfo setWidgetsContainer(WidgetsContainer value) {
      if (value == null) { throw new NullPointerException(); }
      this.containerCase_ = 5;
      this.container_ = value;
      return this;
    }

    // optional .PredictionContainer prediction_container = 6;
    public boolean hasPredictionContainer() {
      return this.containerCase_ == 6;
    }
    public PredictionContainer getPredictionContainer() {
      if (this.containerCase_ == 6) {
        return (PredictionContainer) this.container_;
      }
      return null;
    }
    public ContainerInfo setPredictionContainer(PredictionContainer value) {
      if (value == null) { throw new NullPointerException(); }
      this.containerCase_ = 6;
      this.container_ = value;
      return this;
    }

    // optional .SearchResultContainer search_result_container = 7;
    public boolean hasSearchResultContainer() {
      return this.containerCase_ == 7;
    }
    public SearchResultContainer getSearchResultContainer() {
      if (this.containerCase_ == 7) {
        return (SearchResultContainer) this.container_;
      }
      return null;
    }
    public ContainerInfo setSearchResultContainer(SearchResultContainer value) {
      if (value == null) { throw new NullPointerException(); }
      this.containerCase_ = 7;
      this.container_ = value;
      return this;
    }

    // optional .ShortcutsContainer shortcuts_container = 8;
    public boolean hasShortcutsContainer() {
      return this.containerCase_ == 8;
    }
    public ShortcutsContainer getShortcutsContainer() {
      if (this.containerCase_ == 8) {
        return (ShortcutsContainer) this.container_;
      }
      return null;
    }
    public ContainerInfo setShortcutsContainer(ShortcutsContainer value) {
      if (value == null) { throw new NullPointerException(); }
      this.containerCase_ = 8;
      this.container_ = value;
      return this;
    }

    // optional .SettingsContainer settings_container = 9;
    public boolean hasSettingsContainer() {
      return this.containerCase_ == 9;
    }
    public SettingsContainer getSettingsContainer() {
      if (this.containerCase_ == 9) {
        return (SettingsContainer) this.container_;
      }
      return null;
    }
    public ContainerInfo setSettingsContainer(SettingsContainer value) {
      if (value == null) { throw new NullPointerException(); }
      this.containerCase_ = 9;
      this.container_ = value;
      return this;
    }

    // optional .PredictedHotseatContainer predicted_hotseat_container = 10;
    public boolean hasPredictedHotseatContainer() {
      return this.containerCase_ == 10;
    }
    public PredictedHotseatContainer getPredictedHotseatContainer() {
      if (this.containerCase_ == 10) {
        return (PredictedHotseatContainer) this.container_;
      }
      return null;
    }
    public ContainerInfo setPredictedHotseatContainer(PredictedHotseatContainer value) {
      if (value == null) { throw new NullPointerException(); }
      this.containerCase_ = 10;
      this.container_ = value;
      return this;
    }

    // optional .TaskSwitcherContainer task_switcher_container = 11;
    public boolean hasTaskSwitcherContainer() {
      return this.containerCase_ == 11;
    }
    public TaskSwitcherContainer getTaskSwitcherContainer() {
      if (this.containerCase_ == 11) {
        return (TaskSwitcherContainer) this.container_;
      }
      return null;
    }
    public ContainerInfo setTaskSwitcherContainer(TaskSwitcherContainer value) {
      if (value == null) { throw new NullPointerException(); }
      this.containerCase_ = 11;
      this.container_ = value;
      return this;
    }

    public ContainerInfo() {
      clear();
    }

    public ContainerInfo clear() {
      clearContainer();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.containerCase_ == 1) {
        output.writeMessage(1,
            (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 2) {
        output.writeMessage(2,
            (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 3) {
        output.writeMessage(3,
            (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 4) {
        output.writeMessage(4,
            (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 5) {
        output.writeMessage(5,
            (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 6) {
        output.writeMessage(6,
            (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 7) {
        output.writeMessage(7,
            (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 8) {
        output.writeMessage(8,
            (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 9) {
        output.writeMessage(9,
            (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 10) {
        output.writeMessage(10,
            (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 11) {
        output.writeMessage(11,
            (com.google.protobuf.nano.MessageNano) this.container_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.containerCase_ == 1) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1,
              (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 2) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2,
              (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 3) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3,
              (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 4) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(4,
              (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 5) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(5,
              (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 6) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(6,
              (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 7) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(7,
              (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 8) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(8,
              (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 9) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(9,
              (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 10) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(10,
              (com.google.protobuf.nano.MessageNano) this.container_);
      }
      if (this.containerCase_ == 11) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(11,
              (com.google.protobuf.nano.MessageNano) this.container_);
      }
      return size;
    }

    @Override
    public ContainerInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (!(this.containerCase_ == 1)) {
              this.container_ = new WorkspaceContainer();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.container_);
            this.containerCase_ = 1;
            break;
          }
          case 18: {
            if (!(this.containerCase_ == 2)) {
              this.container_ = new HotseatContainer();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.container_);
            this.containerCase_ = 2;
            break;
          }
          case 26: {
            if (!(this.containerCase_ == 3)) {
              this.container_ = new FolderContainer();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.container_);
            this.containerCase_ = 3;
            break;
          }
          case 34: {
            if (!(this.containerCase_ == 4)) {
              this.container_ = new AllAppsContainer();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.container_);
            this.containerCase_ = 4;
            break;
          }
          case 42: {
            if (!(this.containerCase_ == 5)) {
              this.container_ = new WidgetsContainer();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.container_);
            this.containerCase_ = 5;
            break;
          }
          case 50: {
            if (!(this.containerCase_ == 6)) {
              this.container_ = new PredictionContainer();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.container_);
            this.containerCase_ = 6;
            break;
          }
          case 58: {
            if (!(this.containerCase_ == 7)) {
              this.container_ = new SearchResultContainer();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.container_);
            this.containerCase_ = 7;
            break;
          }
          case 66: {
            if (!(this.containerCase_ == 8)) {
              this.container_ = new ShortcutsContainer();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.container_);
            this.containerCase_ = 8;
            break;
          }
          case 74: {
            if (!(this.containerCase_ == 9)) {
              this.container_ = new SettingsContainer();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.container_);
            this.containerCase_ = 9;
            break;
          }
          case 82: {
            if (!(this.containerCase_ == 10)) {
              this.container_ = new PredictedHotseatContainer();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.container_);
            this.containerCase_ = 10;
            break;
          }
          case 90: {
            if (!(this.containerCase_ == 11)) {
              this.container_ = new TaskSwitcherContainer();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.container_);
            this.containerCase_ = 11;
            break;
          }
        }
      }
    }

    public static ContainerInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ContainerInfo(), data);
    }

    public static ContainerInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ContainerInfo().mergeFrom(input);
    }
  }

  public static final class AllAppsContainer extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AllAppsContainer[] _emptyArray;
    public static AllAppsContainer[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AllAppsContainer[0];
          }
        }
      }
      return _emptyArray;
    }

    public AllAppsContainer() {
      clear();
    }

    public AllAppsContainer clear() {
      cachedSize = -1;
      return this;
    }

    @Override
    public AllAppsContainer mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }

    public static AllAppsContainer parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AllAppsContainer(), data);
    }

    public static AllAppsContainer parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AllAppsContainer().mergeFrom(input);
    }
  }

  public static final class WidgetsContainer extends
      com.google.protobuf.nano.MessageNano {

    private static volatile WidgetsContainer[] _emptyArray;
    public static WidgetsContainer[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new WidgetsContainer[0];
          }
        }
      }
      return _emptyArray;
    }

    public WidgetsContainer() {
      clear();
    }

    public WidgetsContainer clear() {
      cachedSize = -1;
      return this;
    }

    @Override
    public WidgetsContainer mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }

    public static WidgetsContainer parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new WidgetsContainer(), data);
    }

    public static WidgetsContainer parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new WidgetsContainer().mergeFrom(input);
    }
  }

  public static final class PredictionContainer extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PredictionContainer[] _emptyArray;
    public static PredictionContainer[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PredictionContainer[0];
          }
        }
      }
      return _emptyArray;
    }

    public PredictionContainer() {
      clear();
    }

    public PredictionContainer clear() {
      cachedSize = -1;
      return this;
    }

    @Override
    public PredictionContainer mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }

    public static PredictionContainer parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PredictionContainer(), data);
    }

    public static PredictionContainer parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PredictionContainer().mergeFrom(input);
    }
  }

  public static final class SearchResultContainer extends
      com.google.protobuf.nano.MessageNano {
    public static final int WORKSPACE_FIELD_NUMBER = 2;
    public static final int ALL_APPS_CONTAINER_FIELD_NUMBER = 3;
    private int parentContainerCase_ = 0;
    private Object parentContainer_;
    public int getParentContainerCase() {
      return this.parentContainerCase_;
    }
    public SearchResultContainer clearParentContainer() {
      this.parentContainerCase_ = 0;
      this.parentContainer_ = null;
      return this;
    }

    private static volatile SearchResultContainer[] _emptyArray;
    public static SearchResultContainer[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SearchResultContainer[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 query_length = 1;
    public int queryLength;

    // optional .WorkspaceContainer workspace = 2;
    public boolean hasWorkspace() {
      return this.parentContainerCase_ == 2;
    }
    public WorkspaceContainer getWorkspace() {
      if (this.parentContainerCase_ == 2) {
        return (WorkspaceContainer) this.parentContainer_;
      }
      return null;
    }
    public SearchResultContainer setWorkspace(WorkspaceContainer value) {
      if (value == null) { throw new NullPointerException(); }
      this.parentContainerCase_ = 2;
      this.parentContainer_ = value;
      return this;
    }

    // optional .AllAppsContainer all_apps_container = 3;
    public boolean hasAllAppsContainer() {
      return this.parentContainerCase_ == 3;
    }
    public AllAppsContainer getAllAppsContainer() {
      if (this.parentContainerCase_ == 3) {
        return (AllAppsContainer) this.parentContainer_;
      }
      return null;
    }
    public SearchResultContainer setAllAppsContainer(AllAppsContainer value) {
      if (value == null) { throw new NullPointerException(); }
      this.parentContainerCase_ = 3;
      this.parentContainer_ = value;
      return this;
    }

    public SearchResultContainer() {
      clear();
    }

    public SearchResultContainer clear() {
      queryLength = 0;
      clearParentContainer();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.queryLength != 0) {
        output.writeInt32(1, this.queryLength);
      }
      if (this.parentContainerCase_ == 2) {
        output.writeMessage(2,
            (com.google.protobuf.nano.MessageNano) this.parentContainer_);
      }
      if (this.parentContainerCase_ == 3) {
        output.writeMessage(3,
            (com.google.protobuf.nano.MessageNano) this.parentContainer_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.queryLength != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.queryLength);
      }
      if (this.parentContainerCase_ == 2) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2,
              (com.google.protobuf.nano.MessageNano) this.parentContainer_);
      }
      if (this.parentContainerCase_ == 3) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3,
              (com.google.protobuf.nano.MessageNano) this.parentContainer_);
      }
      return size;
    }

    @Override
    public SearchResultContainer mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.queryLength = input.readInt32();
            break;
          }
          case 18: {
            if (!(this.parentContainerCase_ == 2)) {
              this.parentContainer_ = new WorkspaceContainer();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.parentContainer_);
            this.parentContainerCase_ = 2;
            break;
          }
          case 26: {
            if (!(this.parentContainerCase_ == 3)) {
              this.parentContainer_ = new AllAppsContainer();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.parentContainer_);
            this.parentContainerCase_ = 3;
            break;
          }
        }
      }
    }

    public static SearchResultContainer parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new SearchResultContainer(), data);
    }

    public static SearchResultContainer parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SearchResultContainer().mergeFrom(input);
    }
  }

  public static final class ShortcutsContainer extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ShortcutsContainer[] _emptyArray;
    public static ShortcutsContainer[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ShortcutsContainer[0];
          }
        }
      }
      return _emptyArray;
    }

    public ShortcutsContainer() {
      clear();
    }

    public ShortcutsContainer clear() {
      cachedSize = -1;
      return this;
    }

    @Override
    public ShortcutsContainer mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }

    public static ShortcutsContainer parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ShortcutsContainer(), data);
    }

    public static ShortcutsContainer parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ShortcutsContainer().mergeFrom(input);
    }
  }

  public static final class SettingsContainer extends
      com.google.protobuf.nano.MessageNano {

    private static volatile SettingsContainer[] _emptyArray;
    public static SettingsContainer[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SettingsContainer[0];
          }
        }
      }
      return _emptyArray;
    }

    public SettingsContainer() {
      clear();
    }

    public SettingsContainer clear() {
      cachedSize = -1;
      return this;
    }

    @Override
    public SettingsContainer mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }

    public static SettingsContainer parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new SettingsContainer(), data);
    }

    public static SettingsContainer parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SettingsContainer().mergeFrom(input);
    }
  }

  public static final class TaskSwitcherContainer extends
      com.google.protobuf.nano.MessageNano {

    private static volatile TaskSwitcherContainer[] _emptyArray;
    public static TaskSwitcherContainer[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TaskSwitcherContainer[0];
          }
        }
      }
      return _emptyArray;
    }

    public TaskSwitcherContainer() {
      clear();
    }

    public TaskSwitcherContainer clear() {
      cachedSize = -1;
      return this;
    }

    @Override
    public TaskSwitcherContainer mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }

    public static TaskSwitcherContainer parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TaskSwitcherContainer(), data);
    }

    public static TaskSwitcherContainer parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TaskSwitcherContainer().mergeFrom(input);
    }
  }

  public static final class Application extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Application[] _emptyArray;
    public static Application[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Application[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string package_name = 1;
    public String packageName;

    // optional string component_name = 2;
    public String componentName;

    public Application() {
      clear();
    }

    public Application clear() {
      packageName = "";
      componentName = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.packageName.equals("")) {
        output.writeString(1, this.packageName);
      }
      if (!this.componentName.equals("")) {
        output.writeString(2, this.componentName);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.packageName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.packageName);
      }
      if (!this.componentName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.componentName);
      }
      return size;
    }

    @Override
    public Application mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.packageName = input.readString();
            break;
          }
          case 18: {
            this.componentName = input.readString();
            break;
          }
        }
      }
    }

    public static Application parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Application(), data);
    }

    public static Application parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Application().mergeFrom(input);
    }
  }

  public static final class Shortcut extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Shortcut[] _emptyArray;
    public static Shortcut[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Shortcut[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string shortcut_name = 1;
    public String shortcutName;

    public Shortcut() {
      clear();
    }

    public Shortcut clear() {
      shortcutName = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.shortcutName.equals("")) {
        output.writeString(1, this.shortcutName);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.shortcutName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.shortcutName);
      }
      return size;
    }

    @Override
    public Shortcut mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.shortcutName = input.readString();
            break;
          }
        }
      }
    }

    public static Shortcut parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Shortcut(), data);
    }

    public static Shortcut parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Shortcut().mergeFrom(input);
    }
  }

  public static final class Widget extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Widget[] _emptyArray;
    public static Widget[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Widget[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 span_x = 1 [default = 1];
    public int spanX;

    // optional int32 span_y = 2 [default = 1];
    public int spanY;

    // optional int32 app_widget_id = 3;
    public int appWidgetId;

    // optional string package_name = 4;
    public String packageName;

    // optional string component_name = 5;
    public String componentName;

    public Widget() {
      clear();
    }

    public Widget clear() {
      spanX = 1;
      spanY = 1;
      appWidgetId = 0;
      packageName = "";
      componentName = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.spanX != 1) {
        output.writeInt32(1, this.spanX);
      }
      if (this.spanY != 1) {
        output.writeInt32(2, this.spanY);
      }
      if (this.appWidgetId != 0) {
        output.writeInt32(3, this.appWidgetId);
      }
      if (!this.packageName.equals("")) {
        output.writeString(4, this.packageName);
      }
      if (!this.componentName.equals("")) {
        output.writeString(5, this.componentName);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.spanX != 1) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.spanX);
      }
      if (this.spanY != 1) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.spanY);
      }
      if (this.appWidgetId != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.appWidgetId);
      }
      if (!this.packageName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.packageName);
      }
      if (!this.componentName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.componentName);
      }
      return size;
    }

    @Override
    public Widget mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.spanX = input.readInt32();
            break;
          }
          case 16: {
            this.spanY = input.readInt32();
            break;
          }
          case 24: {
            this.appWidgetId = input.readInt32();
            break;
          }
          case 34: {
            this.packageName = input.readString();
            break;
          }
          case 42: {
            this.componentName = input.readString();
            break;
          }
        }
      }
    }

    public static Widget parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Widget(), data);
    }

    public static Widget parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Widget().mergeFrom(input);
    }
  }

  public static final class Task extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Task[] _emptyArray;
    public static Task[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Task[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string package_name = 1;
    public String packageName;

    // optional string component_name = 2;
    public String componentName;

    // optional int32 index = 3;
    public int index;

    public Task() {
      clear();
    }

    public Task clear() {
      packageName = "";
      componentName = "";
      index = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.packageName.equals("")) {
        output.writeString(1, this.packageName);
      }
      if (!this.componentName.equals("")) {
        output.writeString(2, this.componentName);
      }
      if (this.index != 0) {
        output.writeInt32(3, this.index);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.packageName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.packageName);
      }
      if (!this.componentName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.componentName);
      }
      if (this.index != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.index);
      }
      return size;
    }

    @Override
    public Task mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.packageName = input.readString();
            break;
          }
          case 18: {
            this.componentName = input.readString();
            break;
          }
          case 24: {
            this.index = input.readInt32();
            break;
          }
        }
      }
    }

    public static Task parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Task(), data);
    }

    public static Task parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Task().mergeFrom(input);
    }
  }

  public static final class FolderIcon extends
      com.google.protobuf.nano.MessageNano {

    private static volatile FolderIcon[] _emptyArray;
    public static FolderIcon[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new FolderIcon[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 cardinality = 1;
    public int cardinality;

    // optional .FromState from_label_state = 2;
    public int fromLabelState;

    // optional .ToState to_label_state = 3;
    public int toLabelState;

    // optional string label_info = 4;
    public String labelInfo;

    public FolderIcon() {
      clear();
    }

    public FolderIcon clear() {
      cardinality = 0;
      fromLabelState = FromState.FROM_STATE_UNSPECIFIED;
      toLabelState = ToState.TO_STATE_UNSPECIFIED;
      labelInfo = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.cardinality != 0) {
        output.writeInt32(1, this.cardinality);
      }
      if (this.fromLabelState != FromState.FROM_STATE_UNSPECIFIED) {
        output.writeInt32(2, this.fromLabelState);
      }
      if (this.toLabelState != ToState.TO_STATE_UNSPECIFIED) {
        output.writeInt32(3, this.toLabelState);
      }
      if (!this.labelInfo.equals("")) {
        output.writeString(4, this.labelInfo);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.cardinality != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.cardinality);
      }
      if (this.fromLabelState != FromState.FROM_STATE_UNSPECIFIED) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(2, this.fromLabelState);
      }
      if (this.toLabelState != ToState.TO_STATE_UNSPECIFIED) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(3, this.toLabelState);
      }
      if (!this.labelInfo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.labelInfo);
      }
      return size;
    }

    @Override
    public FolderIcon mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.cardinality = input.readInt32();
            break;
          }
          case 16: {
            int value = input.readInt32();
            switch (value) {
              case FromState.FROM_STATE_UNSPECIFIED:
              case FromState.FROM_EMPTY:
              case FromState.FROM_CUSTOM:
              case FromState.FROM_SUGGESTED:
                this.fromLabelState = value;
                break;
            }
            break;
          }
          case 24: {
            int value = input.readInt32();
            switch (value) {
              case ToState.TO_STATE_UNSPECIFIED:
              case ToState.UNCHANGED:
              case ToState.TO_SUGGESTION0:
              case ToState.TO_SUGGESTION1_WITH_VALID_PRIMARY:
              case ToState.TO_SUGGESTION1_WITH_EMPTY_PRIMARY:
              case ToState.TO_SUGGESTION2_WITH_VALID_PRIMARY:
              case ToState.TO_SUGGESTION2_WITH_EMPTY_PRIMARY:
              case ToState.TO_SUGGESTION3_WITH_VALID_PRIMARY:
              case ToState.TO_SUGGESTION3_WITH_EMPTY_PRIMARY:
              case ToState.TO_EMPTY_WITH_VALID_PRIMARY:
              case ToState.TO_EMPTY_WITH_VALID_SUGGESTIONS_AND_EMPTY_PRIMARY:
              case ToState.TO_EMPTY_WITH_EMPTY_SUGGESTIONS:
              case ToState.TO_EMPTY_WITH_SUGGESTIONS_DISABLED:
              case ToState.TO_CUSTOM_WITH_VALID_PRIMARY:
              case ToState.TO_CUSTOM_WITH_VALID_SUGGESTIONS_AND_EMPTY_PRIMARY:
              case ToState.TO_CUSTOM_WITH_EMPTY_SUGGESTIONS:
              case ToState.TO_CUSTOM_WITH_SUGGESTIONS_DISABLED:
                this.toLabelState = value;
                break;
            }
            break;
          }
          case 34: {
            this.labelInfo = input.readString();
            break;
          }
        }
      }
    }

    public static FolderIcon parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new FolderIcon(), data);
    }

    public static FolderIcon parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new FolderIcon().mergeFrom(input);
    }
  }

  public static final class WorkspaceContainer extends
      com.google.protobuf.nano.MessageNano {

    private static volatile WorkspaceContainer[] _emptyArray;
    public static WorkspaceContainer[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new WorkspaceContainer[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 page_index = 1 [default = -2];
    public int pageIndex;

    // optional int32 grid_x = 2 [default = -1];
    public int gridX;

    // optional int32 grid_y = 3 [default = -1];
    public int gridY;

    public WorkspaceContainer() {
      clear();
    }

    public WorkspaceContainer clear() {
      pageIndex = -2;
      gridX = -1;
      gridY = -1;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.pageIndex != -2) {
        output.writeInt32(1, this.pageIndex);
      }
      if (this.gridX != -1) {
        output.writeInt32(2, this.gridX);
      }
      if (this.gridY != -1) {
        output.writeInt32(3, this.gridY);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.pageIndex != -2) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.pageIndex);
      }
      if (this.gridX != -1) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.gridX);
      }
      if (this.gridY != -1) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.gridY);
      }
      return size;
    }

    @Override
    public WorkspaceContainer mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.pageIndex = input.readInt32();
            break;
          }
          case 16: {
            this.gridX = input.readInt32();
            break;
          }
          case 24: {
            this.gridY = input.readInt32();
            break;
          }
        }
      }
    }

    public static WorkspaceContainer parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new WorkspaceContainer(), data);
    }

    public static WorkspaceContainer parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new WorkspaceContainer().mergeFrom(input);
    }
  }

  public static final class HotseatContainer extends
      com.google.protobuf.nano.MessageNano {

    private static volatile HotseatContainer[] _emptyArray;
    public static HotseatContainer[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new HotseatContainer[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 index = 1;
    public int index;

    public HotseatContainer() {
      clear();
    }

    public HotseatContainer clear() {
      index = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.index != 0) {
        output.writeInt32(1, this.index);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.index != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.index);
      }
      return size;
    }

    @Override
    public HotseatContainer mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.index = input.readInt32();
            break;
          }
        }
      }
    }

    public static HotseatContainer parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new HotseatContainer(), data);
    }

    public static HotseatContainer parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new HotseatContainer().mergeFrom(input);
    }
  }

  public static final class PredictedHotseatContainer extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PredictedHotseatContainer[] _emptyArray;
    public static PredictedHotseatContainer[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PredictedHotseatContainer[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 index = 1;
    public int index;

    // optional int32 cardinality = 2;
    public int cardinality;

    public PredictedHotseatContainer() {
      clear();
    }

    public PredictedHotseatContainer clear() {
      index = 0;
      cardinality = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.index != 0) {
        output.writeInt32(1, this.index);
      }
      if (this.cardinality != 0) {
        output.writeInt32(2, this.cardinality);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.index != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.index);
      }
      if (this.cardinality != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.cardinality);
      }
      return size;
    }

    @Override
    public PredictedHotseatContainer mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.index = input.readInt32();
            break;
          }
          case 16: {
            this.cardinality = input.readInt32();
            break;
          }
        }
      }
    }

    public static PredictedHotseatContainer parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PredictedHotseatContainer(), data);
    }

    public static PredictedHotseatContainer parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PredictedHotseatContainer().mergeFrom(input);
    }
  }

  public static final class FolderContainer extends
      com.google.protobuf.nano.MessageNano {
    public static final int WORKSPACE_FIELD_NUMBER = 4;
    public static final int HOTSEAT_FIELD_NUMBER = 5;
    private int parentContainerCase_ = 0;
    private Object parentContainer_;
    public int getParentContainerCase() {
      return this.parentContainerCase_;
    }
    public FolderContainer clearParentContainer() {
      this.parentContainerCase_ = 0;
      this.parentContainer_ = null;
      return this;
    }

    private static volatile FolderContainer[] _emptyArray;
    public static FolderContainer[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new FolderContainer[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 page_index = 1 [default = -1];
    public int pageIndex;

    // optional int32 grid_x = 2 [default = -1];
    public int gridX;

    // optional int32 grid_y = 3 [default = -1];
    public int gridY;

    // optional .WorkspaceContainer workspace = 4;
    public boolean hasWorkspace() {
      return this.parentContainerCase_ == 4;
    }
    public WorkspaceContainer getWorkspace() {
      if (this.parentContainerCase_ == 4) {
        return (WorkspaceContainer) this.parentContainer_;
      }
      return null;
    }
    public FolderContainer setWorkspace(WorkspaceContainer value) {
      if (value == null) { throw new NullPointerException(); }
      this.parentContainerCase_ = 4;
      this.parentContainer_ = value;
      return this;
    }

    // optional .HotseatContainer hotseat = 5;
    public boolean hasHotseat() {
      return this.parentContainerCase_ == 5;
    }
    public HotseatContainer getHotseat() {
      if (this.parentContainerCase_ == 5) {
        return (HotseatContainer) this.parentContainer_;
      }
      return null;
    }
    public FolderContainer setHotseat(HotseatContainer value) {
      if (value == null) { throw new NullPointerException(); }
      this.parentContainerCase_ = 5;
      this.parentContainer_ = value;
      return this;
    }

    public FolderContainer() {
      clear();
    }

    public FolderContainer clear() {
      pageIndex = -1;
      gridX = -1;
      gridY = -1;
      clearParentContainer();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.pageIndex != -1) {
        output.writeInt32(1, this.pageIndex);
      }
      if (this.gridX != -1) {
        output.writeInt32(2, this.gridX);
      }
      if (this.gridY != -1) {
        output.writeInt32(3, this.gridY);
      }
      if (this.parentContainerCase_ == 4) {
        output.writeMessage(4,
            (com.google.protobuf.nano.MessageNano) this.parentContainer_);
      }
      if (this.parentContainerCase_ == 5) {
        output.writeMessage(5,
            (com.google.protobuf.nano.MessageNano) this.parentContainer_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.pageIndex != -1) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.pageIndex);
      }
      if (this.gridX != -1) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.gridX);
      }
      if (this.gridY != -1) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.gridY);
      }
      if (this.parentContainerCase_ == 4) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(4,
              (com.google.protobuf.nano.MessageNano) this.parentContainer_);
      }
      if (this.parentContainerCase_ == 5) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(5,
              (com.google.protobuf.nano.MessageNano) this.parentContainer_);
      }
      return size;
    }

    @Override
    public FolderContainer mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.pageIndex = input.readInt32();
            break;
          }
          case 16: {
            this.gridX = input.readInt32();
            break;
          }
          case 24: {
            this.gridY = input.readInt32();
            break;
          }
          case 34: {
            if (!(this.parentContainerCase_ == 4)) {
              this.parentContainer_ = new WorkspaceContainer();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.parentContainer_);
            this.parentContainerCase_ = 4;
            break;
          }
          case 42: {
            if (!(this.parentContainerCase_ == 5)) {
              this.parentContainer_ = new HotseatContainer();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.parentContainer_);
            this.parentContainerCase_ = 5;
            break;
          }
        }
      }
    }

    public static FolderContainer parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new FolderContainer(), data);
    }

    public static FolderContainer parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new FolderContainer().mergeFrom(input);
    }
  }
}
