// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.android.launcher3.tracing.nano;

@SuppressWarnings("hiding")
public final class LauncherTraceEntryProto extends
    com.google.protobuf.nano.MessageNano {

  private static volatile LauncherTraceEntryProto[] _emptyArray;
  public static LauncherTraceEntryProto[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new LauncherTraceEntryProto[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional fixed64 elapsed_realtime_nanos = 1;
  public long elapsedRealtimeNanos;

  // optional .com.android.launcher3.tracing.nano.LauncherTraceProto launcher = 3;
  public LauncherTraceProto launcher;

  public LauncherTraceEntryProto() {
    clear();
  }

  public LauncherTraceEntryProto clear() {
    elapsedRealtimeNanos = 0L;
    launcher = null;
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (this.elapsedRealtimeNanos != 0L) {
      output.writeFixed64(1, this.elapsedRealtimeNanos);
    }
    if (this.launcher != null) {
      output.writeMessage(3, this.launcher);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (this.elapsedRealtimeNanos != 0L) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeFixed64Size(1, this.elapsedRealtimeNanos);
    }
    if (this.launcher != null) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeMessageSize(3, this.launcher);
    }
    return size;
  }

  @Override
  public LauncherTraceEntryProto mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 9: {
          this.elapsedRealtimeNanos = input.readFixed64();
          break;
        }
        case 26: {
          if (this.launcher == null) {
            this.launcher = new LauncherTraceProto();
          }
          input.readMessage(this.launcher);
          break;
        }
      }
    }
  }

  public static LauncherTraceEntryProto parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new LauncherTraceEntryProto(), data);
  }

  public static LauncherTraceEntryProto parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new LauncherTraceEntryProto().mergeFrom(input);
  }
}
