// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.android.launcher3.tracing.nano;

@SuppressWarnings("hiding")
public final class LauncherTraceProto extends
    com.google.protobuf.nano.MessageNano {

  private static volatile LauncherTraceProto[] _emptyArray;
  public static LauncherTraceProto[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new LauncherTraceProto[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional .com.android.launcher3.tracing.nano.TouchInteractionServiceProto touch_interaction_service = 1;
  public TouchInteractionServiceProto touchInteractionService;

  public LauncherTraceProto() {
    clear();
  }

  public LauncherTraceProto clear() {
    touchInteractionService = null;
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (this.touchInteractionService != null) {
      output.writeMessage(1, this.touchInteractionService);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (this.touchInteractionService != null) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeMessageSize(1, this.touchInteractionService);
    }
    return size;
  }

  @Override
  public LauncherTraceProto mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 10: {
          if (this.touchInteractionService == null) {
            this.touchInteractionService = new TouchInteractionServiceProto();
          }
          input.readMessage(this.touchInteractionService);
          break;
        }
      }
    }
  }

  public static LauncherTraceProto parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new LauncherTraceProto(), data);
  }

  public static LauncherTraceProto parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new LauncherTraceProto().mergeFrom(input);
  }
}
