// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.android.launcher3.tracing.nano;

@SuppressWarnings("hiding")
public final class TouchInteractionServiceProto extends
    com.google.protobuf.nano.MessageNano {

  private static volatile TouchInteractionServiceProto[] _emptyArray;
  public static TouchInteractionServiceProto[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new TouchInteractionServiceProto[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional bool service_connected = 1;
  public boolean serviceConnected;

  public TouchInteractionServiceProto() {
    clear();
  }

  public TouchInteractionServiceProto clear() {
    serviceConnected = false;
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (this.serviceConnected != false) {
      output.writeBool(1, this.serviceConnected);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (this.serviceConnected != false) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeBoolSize(1, this.serviceConnected);
    }
    return size;
  }

  @Override
  public TouchInteractionServiceProto mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 8: {
          this.serviceConnected = input.readBool();
          break;
        }
      }
    }
  }

  public static TouchInteractionServiceProto parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new TouchInteractionServiceProto(), data);
  }

  public static TouchInteractionServiceProto parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new TouchInteractionServiceProto().mergeFrom(input);
  }
}
