// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.android.launcher3.userevent.nano;

@SuppressWarnings("hiding")
public interface LauncherLogProto {

  // enum ItemType
  public interface ItemType {
    public static final int DEFAULT_ITEMTYPE = 0;
    public static final int APP_ICON = 1;
    public static final int SHORTCUT = 2;
    public static final int WIDGET = 3;
    public static final int FOLDER_ICON = 4;
    public static final int DEEPSHORTCUT = 5;
    public static final int SEARCHBOX = 6;
    public static final int EDITTEXT = 7;
    public static final int NOTIFICATION = 8;
    public static final int TASK = 9;
    public static final int WEB_APP = 10;
    public static final int TASK_ICON = 11;
  }

  // enum ContainerType
  public interface ContainerType {
    public static final int DEFAULT_CONTAINERTYPE = 0;
    public static final int WORKSPACE = 1;
    public static final int HOTSEAT = 2;
    public static final int FOLDER = 3;
    public static final int ALLAPPS = 4;
    public static final int WIDGETS = 5;
    public static final int OVERVIEW = 6;
    public static final int PREDICTION = 7;
    public static final int SEARCHRESULT = 8;
    public static final int DEEPSHORTCUTS = 9;
    public static final int PINITEM = 10;
    public static final int NAVBAR = 11;
    public static final int TASKSWITCHER = 12;
    public static final int APP = 13;
    public static final int TIP = 14;
    public static final int OTHER_LAUNCHER_APP = 15;
  }

  // enum ControlType
  public interface ControlType {
    public static final int DEFAULT_CONTROLTYPE = 0;
    public static final int ALL_APPS_BUTTON = 1;
    public static final int WIDGETS_BUTTON = 2;
    public static final int WALLPAPER_BUTTON = 3;
    public static final int SETTINGS_BUTTON = 4;
    public static final int REMOVE_TARGET = 5;
    public static final int UNINSTALL_TARGET = 6;
    public static final int APPINFO_TARGET = 7;
    public static final int RESIZE_HANDLE = 8;
    public static final int VERTICAL_SCROLL = 9;
    public static final int HOME_INTENT = 10;
    public static final int BACK_BUTTON = 11;
    public static final int QUICK_SCRUB_BUTTON = 12;
    public static final int CLEAR_ALL_BUTTON = 13;
    public static final int CANCEL_TARGET = 14;
    public static final int TASK_PREVIEW = 15;
    public static final int SPLIT_SCREEN_TARGET = 16;
    public static final int REMOTE_ACTION_SHORTCUT = 17;
    public static final int APP_USAGE_SETTINGS = 18;
    public static final int BACK_GESTURE = 19;
    public static final int UNDO = 20;
    public static final int DISMISS_PREDICTION = 21;
    public static final int HYBRID_HOTSEAT_ACCEPTED = 22;
    public static final int HYBRID_HOTSEAT_CANCELED = 23;
    public static final int OVERVIEW_ACTIONS_SHARE_BUTTON = 24;
    public static final int OVERVIEW_ACTIONS_SCREENSHOT_BUTTON = 25;
    public static final int OVERVIEW_ACTIONS_SELECT_BUTTON = 26;
    public static final int SELECT_MODE_CLOSE_BUTTON = 27;
    public static final int SELECT_MODE_ITEM = 28;
  }

  // enum TipType
  public interface TipType {
    public static final int DEFAULT_NONE = 0;
    public static final int BOUNCE = 1;
    public static final int SWIPE_UP_TEXT = 2;
    public static final int QUICK_SCRUB_TEXT = 3;
    public static final int PREDICTION_TEXT = 4;
    public static final int DWB_TOAST = 5;
    public static final int HYBRID_HOTSEAT = 6;
  }

  public static final class Target extends
      com.google.protobuf.nano.MessageNano {

    // enum Type
    public interface Type {
      public static final int NONE = 0;
      public static final int ITEM = 1;
      public static final int CONTROL = 2;
      public static final int CONTAINER = 3;
    }

    // enum FromFolderLabelState
    public interface FromFolderLabelState {
      public static final int FROM_FOLDER_LABEL_STATE_UNSPECIFIED = 0;
      public static final int FROM_EMPTY = 1;
      public static final int FROM_CUSTOM = 2;
      public static final int FROM_SUGGESTED = 3;
    }

    // enum ToFolderLabelState
    public interface ToFolderLabelState {
      public static final int TO_FOLDER_LABEL_STATE_UNSPECIFIED = 0;
      public static final int TO_SUGGESTION0_WITH_VALID_PRIMARY = 1;
      public static final int TO_SUGGESTION1_WITH_VALID_PRIMARY = 2;
      public static final int TO_SUGGESTION1_WITH_EMPTY_PRIMARY = 3;
      public static final int TO_SUGGESTION2_WITH_VALID_PRIMARY = 4;
      public static final int TO_SUGGESTION2_WITH_EMPTY_PRIMARY = 5;
      public static final int TO_SUGGESTION3_WITH_VALID_PRIMARY = 6;
      public static final int TO_SUGGESTION3_WITH_EMPTY_PRIMARY = 7;
      public static final int TO_EMPTY_WITH_VALID_SUGGESTIONS = 8;
      public static final int TO_EMPTY_WITH_VALID_PRIMARY = 15;
      public static final int TO_EMPTY_WITH_VALID_SUGGESTIONS_AND_EMPTY_PRIMARY = 16;
      public static final int TO_EMPTY_WITH_EMPTY_SUGGESTIONS = 9;
      public static final int TO_EMPTY_WITH_SUGGESTIONS_DISABLED = 10;
      public static final int TO_CUSTOM_WITH_VALID_SUGGESTIONS = 11;
      public static final int TO_CUSTOM_WITH_VALID_PRIMARY = 17;
      public static final int TO_CUSTOM_WITH_VALID_SUGGESTIONS_AND_EMPTY_PRIMARY = 18;
      public static final int TO_CUSTOM_WITH_EMPTY_SUGGESTIONS = 12;
      public static final int TO_CUSTOM_WITH_SUGGESTIONS_DISABLED = 13;
      public static final int UNCHANGED = 14;
    }

    private static volatile Target[] _emptyArray;
    public static Target[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Target[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .userevent.Target.Type type = 1;
    public int type;

    // optional int32 page_index = 2;
    public int pageIndex;

    // optional int32 rank = 3;
    public int rank;

    // optional int32 grid_x = 4;
    public int gridX;

    // optional int32 grid_y = 5;
    public int gridY;

    // optional .userevent.ContainerType container_type = 6;
    public int containerType;

    // optional int32 cardinality = 7;
    public int cardinality;

    // optional .userevent.ControlType control_type = 8;
    public int controlType;

    // optional .userevent.ItemType item_type = 9;
    public int itemType;

    // optional int32 package_name_hash = 10;
    public int packageNameHash;

    // optional int32 component_hash = 11;
    public int componentHash;

    // optional int32 intent_hash = 12;
    public int intentHash;

    // optional int32 span_x = 13 [default = 1];
    public int spanX;

    // optional int32 span_y = 14 [default = 1];
    public int spanY;

    // optional int32 predictedRank = 15;
    public int predictedRank;

    // optional .userevent.TargetExtension extension = 16;
    public LauncherLogExtensions.TargetExtension extension;

    // optional .userevent.TipType tip_type = 17;
    public int tipType;

    // optional int32 search_query_length = 18;
    public int searchQueryLength;

    // optional bool is_work_app = 19;
    public boolean isWorkApp;

    // optional .userevent.Target.FromFolderLabelState from_folder_label_state = 20;
    public int fromFolderLabelState;

    // optional .userevent.Target.ToFolderLabelState to_folder_label_state = 21;
    public int toFolderLabelState;

    public Target() {
      clear();
    }

    public Target clear() {
      type = Type.NONE;
      pageIndex = 0;
      rank = 0;
      gridX = 0;
      gridY = 0;
      containerType = ContainerType.DEFAULT_CONTAINERTYPE;
      cardinality = 0;
      controlType = ControlType.DEFAULT_CONTROLTYPE;
      itemType = ItemType.DEFAULT_ITEMTYPE;
      packageNameHash = 0;
      componentHash = 0;
      intentHash = 0;
      spanX = 1;
      spanY = 1;
      predictedRank = 0;
      extension = null;
      tipType = TipType.DEFAULT_NONE;
      searchQueryLength = 0;
      isWorkApp = false;
      fromFolderLabelState = FromFolderLabelState.FROM_FOLDER_LABEL_STATE_UNSPECIFIED;
      toFolderLabelState = ToFolderLabelState.TO_FOLDER_LABEL_STATE_UNSPECIFIED;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.type != Type.NONE) {
        output.writeInt32(1, this.type);
      }
      if (this.pageIndex != 0) {
        output.writeInt32(2, this.pageIndex);
      }
      if (this.rank != 0) {
        output.writeInt32(3, this.rank);
      }
      if (this.gridX != 0) {
        output.writeInt32(4, this.gridX);
      }
      if (this.gridY != 0) {
        output.writeInt32(5, this.gridY);
      }
      if (this.containerType != ContainerType.DEFAULT_CONTAINERTYPE) {
        output.writeInt32(6, this.containerType);
      }
      if (this.cardinality != 0) {
        output.writeInt32(7, this.cardinality);
      }
      if (this.controlType != ControlType.DEFAULT_CONTROLTYPE) {
        output.writeInt32(8, this.controlType);
      }
      if (this.itemType != ItemType.DEFAULT_ITEMTYPE) {
        output.writeInt32(9, this.itemType);
      }
      if (this.packageNameHash != 0) {
        output.writeInt32(10, this.packageNameHash);
      }
      if (this.componentHash != 0) {
        output.writeInt32(11, this.componentHash);
      }
      if (this.intentHash != 0) {
        output.writeInt32(12, this.intentHash);
      }
      if (this.spanX != 1) {
        output.writeInt32(13, this.spanX);
      }
      if (this.spanY != 1) {
        output.writeInt32(14, this.spanY);
      }
      if (this.predictedRank != 0) {
        output.writeInt32(15, this.predictedRank);
      }
      if (this.extension != null) {
        output.writeMessage(16, this.extension);
      }
      if (this.tipType != TipType.DEFAULT_NONE) {
        output.writeInt32(17, this.tipType);
      }
      if (this.searchQueryLength != 0) {
        output.writeInt32(18, this.searchQueryLength);
      }
      if (this.isWorkApp != false) {
        output.writeBool(19, this.isWorkApp);
      }
      if (this.fromFolderLabelState != FromFolderLabelState.FROM_FOLDER_LABEL_STATE_UNSPECIFIED) {
        output.writeInt32(20, this.fromFolderLabelState);
      }
      if (this.toFolderLabelState != ToFolderLabelState.TO_FOLDER_LABEL_STATE_UNSPECIFIED) {
        output.writeInt32(21, this.toFolderLabelState);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.type != Type.NONE) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.type);
      }
      if (this.pageIndex != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.pageIndex);
      }
      if (this.rank != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.rank);
      }
      if (this.gridX != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.gridX);
      }
      if (this.gridY != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.gridY);
      }
      if (this.containerType != ContainerType.DEFAULT_CONTAINERTYPE) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(6, this.containerType);
      }
      if (this.cardinality != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(7, this.cardinality);
      }
      if (this.controlType != ControlType.DEFAULT_CONTROLTYPE) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(8, this.controlType);
      }
      if (this.itemType != ItemType.DEFAULT_ITEMTYPE) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(9, this.itemType);
      }
      if (this.packageNameHash != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(10, this.packageNameHash);
      }
      if (this.componentHash != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(11, this.componentHash);
      }
      if (this.intentHash != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(12, this.intentHash);
      }
      if (this.spanX != 1) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(13, this.spanX);
      }
      if (this.spanY != 1) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(14, this.spanY);
      }
      if (this.predictedRank != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(15, this.predictedRank);
      }
      if (this.extension != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(16, this.extension);
      }
      if (this.tipType != TipType.DEFAULT_NONE) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(17, this.tipType);
      }
      if (this.searchQueryLength != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(18, this.searchQueryLength);
      }
      if (this.isWorkApp != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(19, this.isWorkApp);
      }
      if (this.fromFolderLabelState != FromFolderLabelState.FROM_FOLDER_LABEL_STATE_UNSPECIFIED) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(20, this.fromFolderLabelState);
      }
      if (this.toFolderLabelState != ToFolderLabelState.TO_FOLDER_LABEL_STATE_UNSPECIFIED) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(21, this.toFolderLabelState);
      }
      return size;
    }

    @Override
    public Target mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case Type.NONE:
              case Type.ITEM:
              case Type.CONTROL:
              case Type.CONTAINER:
                this.type = value;
                break;
            }
            break;
          }
          case 16: {
            this.pageIndex = input.readInt32();
            break;
          }
          case 24: {
            this.rank = input.readInt32();
            break;
          }
          case 32: {
            this.gridX = input.readInt32();
            break;
          }
          case 40: {
            this.gridY = input.readInt32();
            break;
          }
          case 48: {
            int value = input.readInt32();
            switch (value) {
              case ContainerType.DEFAULT_CONTAINERTYPE:
              case ContainerType.WORKSPACE:
              case ContainerType.HOTSEAT:
              case ContainerType.FOLDER:
              case ContainerType.ALLAPPS:
              case ContainerType.WIDGETS:
              case ContainerType.OVERVIEW:
              case ContainerType.PREDICTION:
              case ContainerType.SEARCHRESULT:
              case ContainerType.DEEPSHORTCUTS:
              case ContainerType.PINITEM:
              case ContainerType.NAVBAR:
              case ContainerType.TASKSWITCHER:
              case ContainerType.APP:
              case ContainerType.TIP:
              case ContainerType.OTHER_LAUNCHER_APP:
                this.containerType = value;
                break;
            }
            break;
          }
          case 56: {
            this.cardinality = input.readInt32();
            break;
          }
          case 64: {
            int value = input.readInt32();
            switch (value) {
              case ControlType.DEFAULT_CONTROLTYPE:
              case ControlType.ALL_APPS_BUTTON:
              case ControlType.WIDGETS_BUTTON:
              case ControlType.WALLPAPER_BUTTON:
              case ControlType.SETTINGS_BUTTON:
              case ControlType.REMOVE_TARGET:
              case ControlType.UNINSTALL_TARGET:
              case ControlType.APPINFO_TARGET:
              case ControlType.RESIZE_HANDLE:
              case ControlType.VERTICAL_SCROLL:
              case ControlType.HOME_INTENT:
              case ControlType.BACK_BUTTON:
              case ControlType.QUICK_SCRUB_BUTTON:
              case ControlType.CLEAR_ALL_BUTTON:
              case ControlType.CANCEL_TARGET:
              case ControlType.TASK_PREVIEW:
              case ControlType.SPLIT_SCREEN_TARGET:
              case ControlType.REMOTE_ACTION_SHORTCUT:
              case ControlType.APP_USAGE_SETTINGS:
              case ControlType.BACK_GESTURE:
              case ControlType.UNDO:
              case ControlType.DISMISS_PREDICTION:
              case ControlType.HYBRID_HOTSEAT_ACCEPTED:
              case ControlType.HYBRID_HOTSEAT_CANCELED:
              case ControlType.OVERVIEW_ACTIONS_SHARE_BUTTON:
              case ControlType.OVERVIEW_ACTIONS_SCREENSHOT_BUTTON:
              case ControlType.OVERVIEW_ACTIONS_SELECT_BUTTON:
              case ControlType.SELECT_MODE_CLOSE_BUTTON:
              case ControlType.SELECT_MODE_ITEM:
                this.controlType = value;
                break;
            }
            break;
          }
          case 72: {
            int value = input.readInt32();
            switch (value) {
              case ItemType.DEFAULT_ITEMTYPE:
              case ItemType.APP_ICON:
              case ItemType.SHORTCUT:
              case ItemType.WIDGET:
              case ItemType.FOLDER_ICON:
              case ItemType.DEEPSHORTCUT:
              case ItemType.SEARCHBOX:
              case ItemType.EDITTEXT:
              case ItemType.NOTIFICATION:
              case ItemType.TASK:
              case ItemType.WEB_APP:
              case ItemType.TASK_ICON:
                this.itemType = value;
                break;
            }
            break;
          }
          case 80: {
            this.packageNameHash = input.readInt32();
            break;
          }
          case 88: {
            this.componentHash = input.readInt32();
            break;
          }
          case 96: {
            this.intentHash = input.readInt32();
            break;
          }
          case 104: {
            this.spanX = input.readInt32();
            break;
          }
          case 112: {
            this.spanY = input.readInt32();
            break;
          }
          case 120: {
            this.predictedRank = input.readInt32();
            break;
          }
          case 130: {
            if (this.extension == null) {
              this.extension = new LauncherLogExtensions.TargetExtension();
            }
            input.readMessage(this.extension);
            break;
          }
          case 136: {
            int value = input.readInt32();
            switch (value) {
              case TipType.DEFAULT_NONE:
              case TipType.BOUNCE:
              case TipType.SWIPE_UP_TEXT:
              case TipType.QUICK_SCRUB_TEXT:
              case TipType.PREDICTION_TEXT:
              case TipType.DWB_TOAST:
              case TipType.HYBRID_HOTSEAT:
                this.tipType = value;
                break;
            }
            break;
          }
          case 144: {
            this.searchQueryLength = input.readInt32();
            break;
          }
          case 152: {
            this.isWorkApp = input.readBool();
            break;
          }
          case 160: {
            int value = input.readInt32();
            switch (value) {
              case FromFolderLabelState.FROM_FOLDER_LABEL_STATE_UNSPECIFIED:
              case FromFolderLabelState.FROM_EMPTY:
              case FromFolderLabelState.FROM_CUSTOM:
              case FromFolderLabelState.FROM_SUGGESTED:
                this.fromFolderLabelState = value;
                break;
            }
            break;
          }
          case 168: {
            int value = input.readInt32();
            switch (value) {
              case ToFolderLabelState.TO_FOLDER_LABEL_STATE_UNSPECIFIED:
              case ToFolderLabelState.TO_SUGGESTION0_WITH_VALID_PRIMARY:
              case ToFolderLabelState.TO_SUGGESTION1_WITH_VALID_PRIMARY:
              case ToFolderLabelState.TO_SUGGESTION1_WITH_EMPTY_PRIMARY:
              case ToFolderLabelState.TO_SUGGESTION2_WITH_VALID_PRIMARY:
              case ToFolderLabelState.TO_SUGGESTION2_WITH_EMPTY_PRIMARY:
              case ToFolderLabelState.TO_SUGGESTION3_WITH_VALID_PRIMARY:
              case ToFolderLabelState.TO_SUGGESTION3_WITH_EMPTY_PRIMARY:
              case ToFolderLabelState.TO_EMPTY_WITH_VALID_SUGGESTIONS:
              case ToFolderLabelState.TO_EMPTY_WITH_VALID_PRIMARY:
              case ToFolderLabelState.TO_EMPTY_WITH_VALID_SUGGESTIONS_AND_EMPTY_PRIMARY:
              case ToFolderLabelState.TO_EMPTY_WITH_EMPTY_SUGGESTIONS:
              case ToFolderLabelState.TO_EMPTY_WITH_SUGGESTIONS_DISABLED:
              case ToFolderLabelState.TO_CUSTOM_WITH_VALID_SUGGESTIONS:
              case ToFolderLabelState.TO_CUSTOM_WITH_VALID_PRIMARY:
              case ToFolderLabelState.TO_CUSTOM_WITH_VALID_SUGGESTIONS_AND_EMPTY_PRIMARY:
              case ToFolderLabelState.TO_CUSTOM_WITH_EMPTY_SUGGESTIONS:
              case ToFolderLabelState.TO_CUSTOM_WITH_SUGGESTIONS_DISABLED:
              case ToFolderLabelState.UNCHANGED:
                this.toFolderLabelState = value;
                break;
            }
            break;
          }
        }
      }
    }

    public static Target parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Target(), data);
    }

    public static Target parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Target().mergeFrom(input);
    }
  }

  public static final class Action extends
      com.google.protobuf.nano.MessageNano {

    // enum Type
    public interface Type {
      public static final int TOUCH = 0;
      public static final int AUTOMATED = 1;
      public static final int COMMAND = 2;
      public static final int TIP = 3;
      public static final int SOFT_KEYBOARD = 4;
    }

    // enum Touch
    public interface Touch {
      public static final int TAP = 0;
      public static final int LONGPRESS = 1;
      public static final int DRAGDROP = 2;
      public static final int SWIPE = 3;
      public static final int FLING = 4;
      public static final int PINCH = 5;
      public static final int SWIPE_NOOP = 6;
    }

    // enum Direction
    public interface Direction {
      public static final int NONE = 0;
      public static final int UP = 1;
      public static final int DOWN = 2;
      public static final int LEFT = 3;
      public static final int RIGHT = 4;
      public static final int UPRIGHT = 5;
      public static final int UPLEFT = 6;
    }

    // enum Command
    public interface Command {
      public static final int HOME_INTENT = 0;
      public static final int BACK = 1;
      public static final int ENTRY = 2;
      public static final int CANCEL = 3;
      public static final int CONFIRM = 4;
      public static final int STOP = 5;
      public static final int RECENTS_BUTTON = 6;
      public static final int RESUME = 7;
    }

    private static volatile Action[] _emptyArray;
    public static Action[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Action[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .userevent.Action.Type type = 1;
    public int type;

    // optional .userevent.Action.Touch touch = 2;
    public int touch;

    // optional .userevent.Action.Direction dir = 3;
    public int dir;

    // optional .userevent.Action.Command command = 4;
    public int command;

    // optional bool is_outside = 5;
    public boolean isOutside;

    // optional bool is_state_change = 6;
    public boolean isStateChange;

    public Action() {
      clear();
    }

    public Action clear() {
      type = Type.TOUCH;
      touch = Touch.TAP;
      dir = Direction.NONE;
      command = Command.HOME_INTENT;
      isOutside = false;
      isStateChange = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.type != Type.TOUCH) {
        output.writeInt32(1, this.type);
      }
      if (this.touch != Touch.TAP) {
        output.writeInt32(2, this.touch);
      }
      if (this.dir != Direction.NONE) {
        output.writeInt32(3, this.dir);
      }
      if (this.command != Command.HOME_INTENT) {
        output.writeInt32(4, this.command);
      }
      if (this.isOutside != false) {
        output.writeBool(5, this.isOutside);
      }
      if (this.isStateChange != false) {
        output.writeBool(6, this.isStateChange);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.type != Type.TOUCH) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.type);
      }
      if (this.touch != Touch.TAP) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(2, this.touch);
      }
      if (this.dir != Direction.NONE) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(3, this.dir);
      }
      if (this.command != Command.HOME_INTENT) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(4, this.command);
      }
      if (this.isOutside != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(5, this.isOutside);
      }
      if (this.isStateChange != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(6, this.isStateChange);
      }
      return size;
    }

    @Override
    public Action mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case Type.TOUCH:
              case Type.AUTOMATED:
              case Type.COMMAND:
              case Type.TIP:
              case Type.SOFT_KEYBOARD:
                this.type = value;
                break;
            }
            break;
          }
          case 16: {
            int value = input.readInt32();
            switch (value) {
              case Touch.TAP:
              case Touch.LONGPRESS:
              case Touch.DRAGDROP:
              case Touch.SWIPE:
              case Touch.FLING:
              case Touch.PINCH:
              case Touch.SWIPE_NOOP:
                this.touch = value;
                break;
            }
            break;
          }
          case 24: {
            int value = input.readInt32();
            switch (value) {
              case Direction.NONE:
              case Direction.UP:
              case Direction.DOWN:
              case Direction.LEFT:
              case Direction.RIGHT:
              case Direction.UPRIGHT:
              case Direction.UPLEFT:
                this.dir = value;
                break;
            }
            break;
          }
          case 32: {
            int value = input.readInt32();
            switch (value) {
              case Command.HOME_INTENT:
              case Command.BACK:
              case Command.ENTRY:
              case Command.CANCEL:
              case Command.CONFIRM:
              case Command.STOP:
              case Command.RECENTS_BUTTON:
              case Command.RESUME:
                this.command = value;
                break;
            }
            break;
          }
          case 40: {
            this.isOutside = input.readBool();
            break;
          }
          case 48: {
            this.isStateChange = input.readBool();
            break;
          }
        }
      }
    }

    public static Action parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Action(), data);
    }

    public static Action parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Action().mergeFrom(input);
    }
  }

  public static final class LauncherEvent extends
      com.google.protobuf.nano.MessageNano {

    private static volatile LauncherEvent[] _emptyArray;
    public static LauncherEvent[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new LauncherEvent[0];
          }
        }
      }
      return _emptyArray;
    }

    // required .userevent.Action action = 1;
    public Action action;

    // repeated .userevent.Target src_target = 2;
    public Target[] srcTarget;

    // repeated .userevent.Target dest_target = 3;
    public Target[] destTarget;

    // optional int64 action_duration_millis = 4;
    public long actionDurationMillis;

    // optional int64 elapsed_container_millis = 5;
    public long elapsedContainerMillis;

    // optional int64 elapsed_session_millis = 6;
    public long elapsedSessionMillis;

    // optional bool is_in_multi_window_mode = 7 [deprecated = true];
    public boolean isInMultiWindowMode;

    // optional bool is_in_landscape_mode = 8 [deprecated = true];
    public boolean isInLandscapeMode;

    // optional .userevent.LauncherEventExtension extension = 9;
    public LauncherLogExtensions.LauncherEventExtension extension;

    public LauncherEvent() {
      clear();
    }

    public LauncherEvent clear() {
      action = null;
      srcTarget = Target.emptyArray();
      destTarget = Target.emptyArray();
      actionDurationMillis = 0L;
      elapsedContainerMillis = 0L;
      elapsedSessionMillis = 0L;
      isInMultiWindowMode = false;
      isInLandscapeMode = false;
      extension = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.action != null) {
        output.writeMessage(1, this.action);
      }
      if (this.srcTarget != null && this.srcTarget.length > 0) {
        for (int i = 0; i < this.srcTarget.length; i++) {
          Target element = this.srcTarget[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      if (this.destTarget != null && this.destTarget.length > 0) {
        for (int i = 0; i < this.destTarget.length; i++) {
          Target element = this.destTarget[i];
          if (element != null) {
            output.writeMessage(3, element);
          }
        }
      }
      if (this.actionDurationMillis != 0L) {
        output.writeInt64(4, this.actionDurationMillis);
      }
      if (this.elapsedContainerMillis != 0L) {
        output.writeInt64(5, this.elapsedContainerMillis);
      }
      if (this.elapsedSessionMillis != 0L) {
        output.writeInt64(6, this.elapsedSessionMillis);
      }
      if (this.isInMultiWindowMode != false) {
        output.writeBool(7, this.isInMultiWindowMode);
      }
      if (this.isInLandscapeMode != false) {
        output.writeBool(8, this.isInLandscapeMode);
      }
      if (this.extension != null) {
        output.writeMessage(9, this.extension);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.action != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.action);
      }
      if (this.srcTarget != null && this.srcTarget.length > 0) {
        for (int i = 0; i < this.srcTarget.length; i++) {
          Target element = this.srcTarget[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      if (this.destTarget != null && this.destTarget.length > 0) {
        for (int i = 0; i < this.destTarget.length; i++) {
          Target element = this.destTarget[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(3, element);
          }
        }
      }
      if (this.actionDurationMillis != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(4, this.actionDurationMillis);
      }
      if (this.elapsedContainerMillis != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(5, this.elapsedContainerMillis);
      }
      if (this.elapsedSessionMillis != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(6, this.elapsedSessionMillis);
      }
      if (this.isInMultiWindowMode != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(7, this.isInMultiWindowMode);
      }
      if (this.isInLandscapeMode != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(8, this.isInLandscapeMode);
      }
      if (this.extension != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(9, this.extension);
      }
      return size;
    }

    @Override
    public LauncherEvent mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.action == null) {
              this.action = new Action();
            }
            input.readMessage(this.action);
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.srcTarget == null ? 0 : this.srcTarget.length;
            Target[] newArray =
                new Target[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.srcTarget, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new Target();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new Target();
            input.readMessage(newArray[i]);
            this.srcTarget = newArray;
            break;
          }
          case 26: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 26);
            int i = this.destTarget == null ? 0 : this.destTarget.length;
            Target[] newArray =
                new Target[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.destTarget, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new Target();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new Target();
            input.readMessage(newArray[i]);
            this.destTarget = newArray;
            break;
          }
          case 32: {
            this.actionDurationMillis = input.readInt64();
            break;
          }
          case 40: {
            this.elapsedContainerMillis = input.readInt64();
            break;
          }
          case 48: {
            this.elapsedSessionMillis = input.readInt64();
            break;
          }
          case 56: {
            this.isInMultiWindowMode = input.readBool();
            break;
          }
          case 64: {
            this.isInLandscapeMode = input.readBool();
            break;
          }
          case 74: {
            if (this.extension == null) {
              this.extension = new LauncherLogExtensions.LauncherEventExtension();
            }
            input.readMessage(this.extension);
            break;
          }
        }
      }
    }

    public static LauncherEvent parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new LauncherEvent(), data);
    }

    public static LauncherEvent parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new LauncherEvent().mergeFrom(input);
    }
  }
}
